inputs:
- branch: master
  path: git
  type: git
  service: ${githubconsolidated01}
- branch: master
  path: container-registry
  type: git
  service: ${githubconsolidated01}
- branch: master
  path: .tekton
  type: git
  service: ${githubconsolidated03}
- branch: master
  path: kubernetes-service
  type: git
  service: ${githubconsolidated01}
properties:
- name: apikey
  type: SECURE
  value: ""
- name: clusterName
  type: TEXT
  value: mycluster
- name: defaultBranch
  type: TEXT
  value: master
- name: imageName
  type: TEXT
  value: my-tekton-built-image
- name: manualRepository
  type: TEXT
  value: ${manualRepository}
- name: registryDomain
  type: TEXT
  value: us.icr.io
- name: registryNamespace
  type: TEXT
  value: bjn-tkn-ns
triggers:
- eventListener: event-listener-manual-run
  name: Manual Trigger
  type: manual
- branch: master
  eventListener: event-listener-git-commit
  events:
    push: true
  name: Git Trigger
  type: git
  service: ${githubconsolidated02}
